# Generated by Django 4.2.7 on 2026-04-17 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='downtime',
            field=models.IntegerField(default=0, editable=False, verbose_name='Время простоя техники'),
        ),
        migrations.AddField(
            model_name='servicecompany',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
